-- Category

INSERT INTO CATEGORY VALUES(1,'Légume', SYSDATE(), SYSDATE(), null);
INSERT INTO CATEGORY VALUES(2,'Fruit', SYSDATE(), SYSDATE(), null);
INSERT INTO CATEGORY VALUES(3,'Fromage', SYSDATE(), SYSDATE(), null);
INSERT INTO CATEGORY VALUES(4,'Boisson', SYSDATE(), SYSDATE(), null);
INSERT INTO CATEGORY VALUES(5,'Boisson alcoolisée', SYSDATE(), SYSDATE(), null);
INSERT INTO CATEGORY VALUES(6,'Céréale', SYSDATE(), SYSDATE(), null);
INSERT INTO CATEGORY VALUES(7,'Viande', SYSDATE(), SYSDATE(), null);
INSERT INTO CATEGORY VALUES(8,'Pain', SYSDATE(), SYSDATE(), null);

-- Products

INSERT INTO PRODUCT VALUES(1, 1, 'Aubergine', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(2, 1, 'Poireau', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(3, 1, 'Epinard', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(4, 2, 'Pomme', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(5, 2, 'Abricot', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(6, 2, 'Citron', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(7, 3, 'Morbier', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(8, 3, 'Fromage de chèvre', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(9, 3, 'Camembert', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(10, 4, 'Jus de pomme', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(11, 4, 'Limonade', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(12, 4, 'Jus de fruit', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(13, 5, 'Vin rouge', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(14, 5, 'Vin blanc', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(15, 5, 'Eau de vie', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(16, 6, 'Avoine', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(17, 6, 'Blé', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(18, 6, 'Riz', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(19, 7, 'Boeuf', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(20, 7, 'Porc', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(21, 7, 'Canard', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(22, 8, 'Brioche', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(23, 8, 'Pain blanc', SYSDATE(), SYSDATE(), null);
INSERT INTO PRODUCT VALUES(24, 8, 'Pain complet', SYSDATE(), SYSDATE(), null);

-- Units

INSERT INTO UNIT VALUES(1, 'Unité', SYSDATE(), SYSDATE(), null);
INSERT INTO UNIT VALUES(2, 'Kg', SYSDATE(), SYSDATE(), null);
INSERT INTO UNIT VALUES(3, 'Litres', SYSDATE(), SYSDATE(), null);

commit;